[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.x"
  NPM_VERSION = "10.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Essential for Next.js on Netlify
[functions]
  node_bundler = "esbuild"

# Cache optimization
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"
